"""Shared fixtures for the integration (end-to-end) test suite.

These fixtures talk to a running test stack (see ``docker-compose.test.yml``)
exclusively through HTTP and subprocess-invoked CLIs; nothing here imports
from ``src/`` so the suite validates the deployed image rather than the
in-process code path.
"""

from __future__ import annotations

import json
import subprocess
import time
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Iterable

import pytest
import requests

TEST_DASHBOARD_URL = "http://localhost:18800"
TESTBED_SLUG = "AlexBomber12__pipeline-orchestrator-testbed"
TESTBED_REPO = "AlexBomber12/pipeline-orchestrator-testbed"
TESTBED_DEFAULT_BRANCH = "main"
REPO_DIR = Path(__file__).resolve().parents[2]
EVIDENCE_DIR = REPO_DIR / "tests" / "e2e" / "evidence"

_REQUIRED_SERVICES = {"daemon-test", "web-test", "redis-test"}
_STACK_UP_COMMAND = (
    "docker compose -f docker-compose.test.yml up -d --build"
)


def _running_services() -> set[str]:
    """Return the set of test-stack services currently running."""
    result = subprocess.run(
        [
            "docker",
            "compose",
            "-f",
            "docker-compose.test.yml",
            "ps",
            "--services",
            "--filter",
            "status=running",
        ],
        cwd=str(REPO_DIR),
        capture_output=True,
        text=True,
        check=False,
    )
    return {line.strip() for line in result.stdout.splitlines() if line.strip()}


@pytest.fixture(scope="session", autouse=True)
def ensure_test_stack_up() -> None:
    running = _running_services()
    missing = _REQUIRED_SERVICES - running
    if missing:
        pytest.fail(
            "Test stack is not running. Missing services: "
            f"{sorted(missing)}. Start it with:\n    {_STACK_UP_COMMAND}"
        )

    deadline = time.monotonic() + 30.0
    last_error: str = ""
    while time.monotonic() < deadline:
        try:
            resp = requests.get(f"{TEST_DASHBOARD_URL}/api/states", timeout=2)
            if resp.status_code == 200:
                return
            last_error = f"HTTP {resp.status_code}"
        except requests.RequestException as exc:
            last_error = str(exc)
        time.sleep(1.0)
    pytest.fail(
        f"Dashboard at {TEST_DASHBOARD_URL}/api/states did not return 200 "
        f"within 30s. Last error: {last_error}"
    )


@pytest.fixture(scope="session")
def dashboard_url() -> str:
    return TEST_DASHBOARD_URL


@pytest.fixture(scope="session")
def testbed_url() -> str:
    return f"{TEST_DASHBOARD_URL}/repo/{TESTBED_SLUG}"


@pytest.fixture(scope="session")
def testbed_slug() -> str:
    return TESTBED_SLUG


def _fetch_state(slug: str) -> dict[str, Any] | None:
    resp = requests.get(f"{TEST_DASHBOARD_URL}/api/states", timeout=5)
    resp.raise_for_status()
    for entry in resp.json():
        if entry.get("slug") == slug or entry.get("name") == slug:
            return entry
    return None


@pytest.fixture
def get_state() -> Callable[..., dict[str, Any] | None]:
    def _get(slug: str = TESTBED_SLUG) -> dict[str, Any] | None:
        return _fetch_state(slug)

    return _get


@pytest.fixture
def wait_for_state() -> Callable[..., dict[str, Any]]:
    def _wait(
        states: Iterable[str],
        timeout_sec: float = 30.0,
        slug: str = TESTBED_SLUG,
        poll_interval_sec: float = 1.0,
    ) -> dict[str, Any]:
        wanted = set(states)
        deadline = time.monotonic() + timeout_sec
        last: dict[str, Any] | None = None
        while time.monotonic() < deadline:
            last = _fetch_state(slug)
            if last is not None and last.get("state") in wanted:
                return last
            time.sleep(poll_interval_sec)
        raise TimeoutError(
            f"Slug {slug!r} never reached one of {sorted(wanted)} "
            f"within {timeout_sec}s. Last state: {last}"
        )

    return _wait


def _task_markdown(pr_id: str, title_slug: str, coder: str, priority: int) -> str:
    branch = f"pr-{pr_id.lower().replace('.', '-')}-{title_slug}"
    return (
        f"# {pr_id}: {title_slug.replace('-', ' ')}\n"
        "\n"
        f"Branch: {branch}\n"
        "- Type: feature\n"
        "- Complexity: low\n"
        "- Depends on: none\n"
        f"- Priority: {priority}\n"
        f"- Coder: {coder}\n"
        "\n"
        "## Problem\n"
        "\n"
        "Synthetic task generated by the e2e test harness.\n"
        "\n"
        "## Scope\n"
        "\n"
        "Touch one placeholder file to validate the pipeline end-to-end.\n"
        "\n"
        "## Files to touch\n"
        "\n"
        "`README.md`: append a single line.\n"
        "\n"
        "## Files NOT to touch\n"
        "\n"
        "Anything outside the touch list.\n"
        "\n"
        "## Success criteria\n"
        "\n"
        "1. README.md is updated and the PR is opened against main.\n"
    )


def _normalize_pr_id(pr_id: str) -> str:
    """Return ``pr_id`` in canonical ``PR-<suffix>`` form.

    Both the dashboard's upload endpoint
    (``^PR-[A-Za-z0-9._-]+\\.md$`` in ``src/web/app.py``) and the daemon's
    task-header parser (``^#\\s+PR-...`` in ``src/queue_parser.py``) require
    the ``PR-`` prefix, so callers that pass a bare numeric (e.g. ``"800"``)
    would otherwise be rejected by either the upload (HTTP 422) or the
    daemon when it tries to read the task file.
    """
    suffix = pr_id[3:] if pr_id[:3].upper() == "PR-" else pr_id
    return f"PR-{suffix}"


@pytest.fixture
def make_task_zip(tmp_path: Path) -> Callable[..., Path]:
    def _make(
        pr_id: str,
        title_slug: str,
        coder: str = "any",
        priority: int = 2,
    ) -> Path:
        normalized = _normalize_pr_id(pr_id)
        content = _task_markdown(normalized, title_slug, coder, priority)
        zip_path = tmp_path / f"{normalized}-{title_slug}.zip"
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            zf.writestr(f"{normalized}.md", content)
        return zip_path

    return _make


@pytest.fixture
def upload_zip() -> Callable[[Path], requests.Response]:
    def _upload(zip_path: Path) -> requests.Response:
        with zip_path.open("rb") as fh:
            files = {
                "files": (zip_path.name, fh.read(), "application/zip"),
            }
        return requests.post(
            f"{TEST_DASHBOARD_URL}/repos/{TESTBED_SLUG}/upload-tasks",
            files=files,
            timeout=30,
        )

    return _upload


@pytest.fixture
def take_screenshot(request: pytest.FixtureRequest) -> Callable[[str], Path]:
    def _shot(name: str) -> Path:
        EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)
        page = request.getfixturevalue("page")
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        path = EVIDENCE_DIR / f"{timestamp}-{name}.png"
        page.screenshot(path=str(path), full_page=True)
        return path

    return _shot


def _branch_prefix_for(pr_id: str) -> str:
    """Return the canonical branch prefix the daemon emits for ``pr_id``.

    Mirrors the formula in :func:`_task_markdown` so cleanup can match only
    branches authored by the current test session.
    """
    return f"pr-{pr_id.lower().replace('.', '-')}-"


def _list_owned_testbed_pr_numbers(
    pr_ids: Iterable[str], *, state: str = "open"
) -> set[str]:
    """Return PR numbers in ``state`` whose head branch belongs to one of ``pr_ids``.

    Filtering by head-branch prefix keeps teardown scoped to PRs created by
    this test session, so a parallel CI run or an unrelated PR opened on
    the testbed during the test is never closed. ``state`` accepts any value
    ``gh pr list --state`` does (``open``, ``merged``, ``closed``, ``all``).
    """
    prefixes = tuple(_branch_prefix_for(pid) for pid in pr_ids)
    if not prefixes:
        return set()
    result = subprocess.run(
        [
            "gh",
            "pr",
            "list",
            "-R",
            TESTBED_REPO,
            "--state",
            state,
            "--limit",
            "1000",
            "--json",
            "number,headRefName",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"Failed to list {state} PRs on {TESTBED_REPO} during testbed cleanup "
            f"(exit {result.returncode}): {result.stderr.strip() or result.stdout.strip()}"
        )
    try:
        prs = json.loads(result.stdout or "[]")
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            f"Failed to parse `gh pr list` output during testbed cleanup: {exc}"
        ) from exc
    owned: set[str] = set()
    for pr in prs:
        head = pr.get("headRefName") or ""
        if any(head.startswith(prefix) for prefix in prefixes):
            owned.add(str(pr.get("number")))
    return owned


def _get_testbed_branch_sha(branch: str = TESTBED_DEFAULT_BRANCH) -> str:
    result = subprocess.run(
        [
            "gh",
            "api",
            f"repos/{TESTBED_REPO}/git/ref/heads/{branch}",
            "-q",
            ".object.sha",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"Failed to read {branch!r} HEAD on {TESTBED_REPO} "
            f"(exit {result.returncode}): "
            f"{result.stderr.strip() or result.stdout.strip()}"
        )
    sha = result.stdout.strip()
    if not sha:
        raise RuntimeError(
            f"`gh api` returned empty SHA for {branch!r} on {TESTBED_REPO}"
        )
    return sha


def _reset_testbed_branch(sha: str, branch: str = TESTBED_DEFAULT_BRANCH) -> None:
    """Force-reset the testbed default branch to ``sha``.

    Used after a test-owned PR auto-merges so the next run starts from the
    same baseline the fixture captured at entry. Callers MUST verify with
    :func:`_assert_only_owned_commits_on_branch` first so unrelated commits
    that landed concurrently are not silently discarded.
    """
    result = subprocess.run(
        [
            "gh",
            "api",
            "-X",
            "PATCH",
            f"repos/{TESTBED_REPO}/git/refs/heads/{branch}",
            "-f",
            f"sha={sha}",
            "-F",
            "force=true",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"Failed to reset {branch!r} to {sha} on {TESTBED_REPO} during testbed "
            f"cleanup (exit {result.returncode}): "
            f"{result.stderr.strip() or result.stdout.strip()}"
        )


def _get_pr_merge_sha(number: str) -> str | None:
    """Return the merge commit SHA for ``number`` on the testbed, or None."""
    result = subprocess.run(
        [
            "gh",
            "pr",
            "view",
            number,
            "-R",
            TESTBED_REPO,
            "--json",
            "mergeCommit",
            "-q",
            ".mergeCommit.oid",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"Failed to read merge commit for PR #{number} on {TESTBED_REPO} "
            f"(exit {result.returncode}): "
            f"{result.stderr.strip() or result.stdout.strip()}"
        )
    return result.stdout.strip() or None


def _get_commit_first_parent(sha: str) -> str | None:
    """Return the first-parent SHA of ``sha`` on the testbed, or None at root."""
    result = subprocess.run(
        [
            "gh",
            "api",
            f"repos/{TESTBED_REPO}/commits/{sha}",
            "-q",
            ".parents[0].sha",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"Failed to read commit {sha} on {TESTBED_REPO} during testbed cleanup "
            f"(exit {result.returncode}): "
            f"{result.stderr.strip() or result.stdout.strip()}"
        )
    return result.stdout.strip() or None


def _assert_only_owned_commits_on_branch(
    baseline_sha: str,
    current_sha: str,
    owned_merge_shas: set[str],
    *,
    max_walk: int = 100,
) -> None:
    """Walk first-parent from ``current_sha`` to ``baseline_sha``.

    Raises if any commit on the chain is not in ``owned_merge_shas``, so the
    caller can refuse to rewrite the default branch when an unrelated push
    landed alongside the test-owned merges.
    """
    sha: str | None = current_sha
    walked = 0
    while sha and sha != baseline_sha:
        if sha not in owned_merge_shas:
            raise RuntimeError(
                f"Refusing to reset {TESTBED_DEFAULT_BRANCH} on {TESTBED_REPO}: "
                f"commit {sha} on the first-parent chain is not attributable "
                f"to any test-owned merged PR "
                f"(owned merges={sorted(owned_merge_shas)}). Clean up manually."
            )
        sha = _get_commit_first_parent(sha)
        walked += 1
        if walked > max_walk:
            raise RuntimeError(
                f"Walked {max_walk} commits from {current_sha} without reaching "
                f"baseline {baseline_sha} on {TESTBED_REPO}; aborting reset."
            )
    if sha != baseline_sha:
        raise RuntimeError(
            f"First-parent walk from {current_sha} ended at {sha} instead of "
            f"baseline {baseline_sha} on {TESTBED_REPO}; aborting reset."
        )


def _close_testbed_prs(numbers: Iterable[str]) -> None:
    for number in numbers:
        close = subprocess.run(
            ["gh", "pr", "close", number, "-R", TESTBED_REPO, "--delete-branch"],
            capture_output=True,
            text=True,
            check=False,
        )
        if close.returncode != 0:
            raise RuntimeError(
                f"Failed to close PR #{number} on {TESTBED_REPO} during testbed "
                f"cleanup (exit {close.returncode}): "
                f"{close.stderr.strip() or close.stdout.strip()}"
            )


def _wait_daemon_idle(timeout_sec: float = 60.0) -> None:
    deadline = time.monotonic() + timeout_sec
    last: dict[str, Any] | None = None
    while time.monotonic() < deadline:
        try:
            last = _fetch_state(TESTBED_SLUG)
        except requests.RequestException:
            last = None
        else:
            if (
                last is not None
                and last.get("state") == "IDLE"
                and last.get("current_pr") in (None, "", 0)
            ):
                return
        time.sleep(1.0)
    raise TimeoutError(
        f"Daemon did not reach IDLE for slug {TESTBED_SLUG!r} within "
        f"{timeout_sec}s. Last state: {last}"
    )


@pytest.fixture
def reset_testbed_clean() -> Iterable[Callable[[str], None]]:
    """Yield a registration callback; teardown closes only test-owned PRs.

    Tests must call the yielded ``register(pr_id)`` for each task they upload.
    Teardown closes any open PR whose head branch matches a registered
    PR_ID. Because ``config.test.yml`` enables auto-merge, teardown also
    handles registered PRs that merged: it walks first-parent from the
    current default-branch HEAD back to the SHA captured at fixture entry,
    confirms every commit on that chain is the merge commit of a registered
    test-owned PR, and only then force-resets the branch back to baseline.
    If anything unrelated pushed to the default branch in the meantime, the
    walk raises ``RuntimeError`` instead of silently rewriting history.
    """
    registered: set[str] = set()
    baseline_sha = _get_testbed_branch_sha()

    def register(pr_id: str) -> None:
        registered.add(_normalize_pr_id(pr_id))

    yield register
    open_owned = _list_owned_testbed_pr_numbers(registered, state="open")
    _close_testbed_prs(open_owned)
    merged_owned = _list_owned_testbed_pr_numbers(registered, state="merged")
    if merged_owned:
        current_sha = _get_testbed_branch_sha()
        if current_sha != baseline_sha:
            owned_merge_shas = {
                sha
                for number in merged_owned
                if (sha := _get_pr_merge_sha(number)) is not None
            }
            _assert_only_owned_commits_on_branch(
                baseline_sha, current_sha, owned_merge_shas
            )
            _reset_testbed_branch(baseline_sha)
    _wait_daemon_idle()
