"""Shared fixtures for the integration (end-to-end) test suite.

These fixtures talk to a running test stack (see ``docker-compose.test.yml``)
exclusively through HTTP and subprocess-invoked CLIs; nothing here imports
from ``src/`` so the suite validates the deployed image rather than the
in-process code path.
"""

from __future__ import annotations

import subprocess
import time
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Iterable

import pytest
import requests

TEST_DASHBOARD_URL = "http://localhost:18800"
TESTBED_SLUG = "AlexBomber12__pipeline-orchestrator-testbed"
TESTBED_REPO = "AlexBomber12/pipeline-orchestrator-testbed"
REPO_DIR = Path(__file__).resolve().parents[2]
EVIDENCE_DIR = REPO_DIR / "tests" / "e2e" / "evidence"

_REQUIRED_SERVICES = {"daemon-test", "web-test", "redis-test"}
_STACK_UP_COMMAND = (
    "docker compose -f docker-compose.test.yml up -d --build"
)


def _running_services() -> set[str]:
    """Return the set of test-stack services currently running."""
    result = subprocess.run(
        [
            "docker",
            "compose",
            "-f",
            "docker-compose.test.yml",
            "ps",
            "--services",
            "--filter",
            "status=running",
        ],
        cwd=str(REPO_DIR),
        capture_output=True,
        text=True,
        check=False,
    )
    return {line.strip() for line in result.stdout.splitlines() if line.strip()}


@pytest.fixture(scope="session", autouse=True)
def ensure_test_stack_up() -> None:
    running = _running_services()
    missing = _REQUIRED_SERVICES - running
    if missing:
        pytest.fail(
            "Test stack is not running. Missing services: "
            f"{sorted(missing)}. Start it with:\n    {_STACK_UP_COMMAND}"
        )

    deadline = time.monotonic() + 30.0
    last_error: str = ""
    while time.monotonic() < deadline:
        try:
            resp = requests.get(f"{TEST_DASHBOARD_URL}/api/states", timeout=2)
            if resp.status_code == 200:
                return
            last_error = f"HTTP {resp.status_code}"
        except requests.RequestException as exc:
            last_error = str(exc)
        time.sleep(1.0)
    pytest.fail(
        f"Dashboard at {TEST_DASHBOARD_URL}/api/states did not return 200 "
        f"within 30s. Last error: {last_error}"
    )


@pytest.fixture(scope="session")
def dashboard_url() -> str:
    return TEST_DASHBOARD_URL


@pytest.fixture(scope="session")
def testbed_url() -> str:
    return f"{TEST_DASHBOARD_URL}/repo/{TESTBED_SLUG}"


@pytest.fixture(scope="session")
def testbed_slug() -> str:
    return TESTBED_SLUG


def _fetch_state(slug: str) -> dict[str, Any] | None:
    resp = requests.get(f"{TEST_DASHBOARD_URL}/api/states", timeout=5)
    resp.raise_for_status()
    for entry in resp.json():
        if entry.get("slug") == slug or entry.get("name") == slug:
            return entry
    return None


@pytest.fixture
def get_state() -> Callable[..., dict[str, Any] | None]:
    def _get(slug: str = TESTBED_SLUG) -> dict[str, Any] | None:
        return _fetch_state(slug)

    return _get


@pytest.fixture
def wait_for_state() -> Callable[..., dict[str, Any]]:
    def _wait(
        states: Iterable[str],
        timeout_sec: float = 30.0,
        slug: str = TESTBED_SLUG,
        poll_interval_sec: float = 1.0,
    ) -> dict[str, Any]:
        wanted = set(states)
        deadline = time.monotonic() + timeout_sec
        last: dict[str, Any] | None = None
        while time.monotonic() < deadline:
            last = _fetch_state(slug)
            if last is not None and last.get("state") in wanted:
                return last
            time.sleep(poll_interval_sec)
        raise TimeoutError(
            f"Slug {slug!r} never reached one of {sorted(wanted)} "
            f"within {timeout_sec}s. Last state: {last}"
        )

    return _wait


def _task_markdown(pr_id: str, title_slug: str, coder: str, priority: int) -> str:
    branch = f"pr-{pr_id.lower().replace('.', '-')}-{title_slug}"
    return (
        f"# {pr_id}: {title_slug.replace('-', ' ')}\n"
        "\n"
        f"Branch: {branch}\n"
        "- Type: feature\n"
        "- Complexity: low\n"
        "- Depends on: none\n"
        f"- Priority: {priority}\n"
        f"- Coder: {coder}\n"
        "\n"
        "## Problem\n"
        "\n"
        "Synthetic task generated by the e2e test harness.\n"
        "\n"
        "## Scope\n"
        "\n"
        "Touch one placeholder file to validate the pipeline end-to-end.\n"
        "\n"
        "## Files to touch\n"
        "\n"
        "`README.md`: append a single line.\n"
        "\n"
        "## Files NOT to touch\n"
        "\n"
        "Anything outside the touch list.\n"
        "\n"
        "## Success criteria\n"
        "\n"
        "1. README.md is updated and the PR is opened against main.\n"
    )


def _normalize_pr_id(pr_id: str) -> str:
    """Return ``pr_id`` in canonical ``PR-<suffix>`` form.

    Both the dashboard's upload endpoint
    (``^PR-[A-Za-z0-9._-]+\\.md$`` in ``src/web/app.py``) and the daemon's
    task-header parser (``^#\\s+PR-...`` in ``src/queue_parser.py``) require
    the ``PR-`` prefix, so callers that pass a bare numeric (e.g. ``"800"``)
    would otherwise be rejected by either the upload (HTTP 422) or the
    daemon when it tries to read the task file.
    """
    suffix = pr_id[3:] if pr_id[:3].upper() == "PR-" else pr_id
    return f"PR-{suffix}"


@pytest.fixture
def make_task_zip(tmp_path: Path) -> Callable[..., Path]:
    def _make(
        pr_id: str,
        title_slug: str,
        coder: str = "any",
        priority: int = 2,
    ) -> Path:
        normalized = _normalize_pr_id(pr_id)
        content = _task_markdown(normalized, title_slug, coder, priority)
        zip_path = tmp_path / f"{normalized}-{title_slug}.zip"
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            zf.writestr(f"{normalized}.md", content)
        return zip_path

    return _make


@pytest.fixture
def upload_zip() -> Callable[[Path], requests.Response]:
    def _upload(zip_path: Path) -> requests.Response:
        with zip_path.open("rb") as fh:
            files = {
                "files": (zip_path.name, fh.read(), "application/zip"),
            }
        return requests.post(
            f"{TEST_DASHBOARD_URL}/repos/{TESTBED_SLUG}/upload-tasks",
            files=files,
            timeout=30,
        )

    return _upload


@pytest.fixture
def take_screenshot(request: pytest.FixtureRequest) -> Callable[[str], Path]:
    def _shot(name: str) -> Path:
        EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)
        page = request.getfixturevalue("page")
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        path = EVIDENCE_DIR / f"{timestamp}-{name}.png"
        page.screenshot(path=str(path), full_page=True)
        return path

    return _shot


def _list_open_testbed_pr_numbers() -> set[str]:
    result = subprocess.run(
        [
            "gh",
            "pr",
            "list",
            "-R",
            TESTBED_REPO,
            "--state",
            "open",
            "--json",
            "number",
            "--jq",
            ".[].number",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"Failed to list open PRs on {TESTBED_REPO} during testbed cleanup "
            f"(exit {result.returncode}): {result.stderr.strip() or result.stdout.strip()}"
        )
    return {raw.strip() for raw in result.stdout.splitlines() if raw.strip()}


def _close_testbed_prs(numbers: Iterable[str]) -> None:
    for number in numbers:
        close = subprocess.run(
            ["gh", "pr", "close", number, "-R", TESTBED_REPO, "--delete-branch"],
            capture_output=True,
            text=True,
            check=False,
        )
        if close.returncode != 0:
            raise RuntimeError(
                f"Failed to close PR #{number} on {TESTBED_REPO} during testbed "
                f"cleanup (exit {close.returncode}): "
                f"{close.stderr.strip() or close.stdout.strip()}"
            )


def _wait_daemon_idle(timeout_sec: float = 60.0) -> None:
    deadline = time.monotonic() + timeout_sec
    last: dict[str, Any] | None = None
    while time.monotonic() < deadline:
        last = _fetch_state(TESTBED_SLUG)
        if (
            last is not None
            and last.get("state") == "IDLE"
            and last.get("current_pr") in (None, "", 0)
        ):
            return
        time.sleep(1.0)
    raise TimeoutError(
        f"Daemon did not reach IDLE for slug {TESTBED_SLUG!r} within "
        f"{timeout_sec}s. Last state: {last}"
    )


@pytest.fixture
def reset_testbed_clean() -> Iterable[None]:
    pre_existing = _list_open_testbed_pr_numbers()
    yield
    test_owned = _list_open_testbed_pr_numbers() - pre_existing
    _close_testbed_prs(test_owned)
    _wait_daemon_idle()
